### ISSUE TITLE
sh scripts/pipeline.sh error

### ISSUE THREAD

**Issue by tianxingyzxq** [yl-1993/learn-to-cluster#14] opened 2019-07-12 05:26 UTC
I have download the 1 part testing data, but when i run sh scripts/pipeline.sh,  I encountered the following error:
ave_pre: 0.9732, ave_rec: 0.5245, fscore: 0.6816
th_pos=-1.0, th_iou=1.0, pred_score=./data/work_dir/cfg_0.7_0.75/pretrained_gcn_d.npz, pred_label_fn=./data/work_dir/cfg_0.7_0.75/pretrained_gcn_d_th_iou_1.0_pos_-1.0_pred_label.txt
Traceback (most recent call last):
  File "./post_process/deoverlap.py", line 35, in <module>
    d = np.load(args.pred_score)
  File "/home/tx/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/work_dir/cfg_0.7_0.75/pretrained_gcn_d.npz'
Traceback (most recent call last):
  File "evaluation/evaluate.py", line 31, in <module>
    pred_labels, pred_lb_set = _read_meta(args.pred_labels)
  File "evaluation/evaluate.py", line 15, in _read_meta
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/work_dir/cfg_0.7_0.75/pretrained_gcn_th_iou_1.0_pos_-1.0_pred_label.txt'

**Comment by wuchuanying** [comment] 2019-07-13 09:35
you resloved it？

**Comment by yl-1993** [comment] 2019-07-13 13:04
@tianxingyzxq @wuchuanying Thank you for checking out! It is my fault. I made some changes but do not update the pipeline scripts. It has been fixed through https://github.com/yl-1993/learn-to-cluster/commit/ef861e59f008ff728319c68b79590f7e6f1bac31. Please try again. :)

**Comment by wuchuanying** [comment] 2019-07-13 16:09
@yl-1993 
dump output to ./data/work_dir/cfg_test_0.7_0.75/pretrained_gcn_d.npz
th_pos=-1.0, th_iou=1.0, pred_score=./data/work_dir/cfg_test_0.7_0.75/pretrained_gcn_d.npz, pred_label_fn=./data/work_dir/cfg_test_0.7_0.75/pretrained_gcn_d_th_iou_1.0_pos_-1.0_pred_label.txt
Traceback (most recent call last):
  File "./post_process/deoverlap.py", line 37, in <module>
    meta = d['meta'].item()
  File "/root/miniconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
Traceback (most recent call last):
  File "evaluation/evaluate.py", line 31, in <module>
    pred_labels, pred_lb_set = _read_meta(args.pred_labels)
  File "evaluation/evaluate.py", line 15, in _read_meta
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/work_dir/cfg_test_0.7_0.75/pretrained_gcn_d_th_iou_1.0_pos_-1.0_pred_label.txt'

**Comment by yl-1993** [comment] 2019-07-13 16:53
@wuchuanying Thanks for reporting! I think the issue is raised by the version of `numpy`, it is fixed by https://github.com/yl-1993/learn-to-cluster/commit/a9946994ecbe44edc7f253ee288a3affc6553131. Another solution is to downgrade the numpy version to 1.16.2. You can try again now. Feel free to keep reporting more bugs. :)

**Comment by wuchuanying** [comment] 2019-07-14 01:06
Thanks@yl-1993

**Closed** 2019-08-06 12:20 UTC
